first_number = float(input("Enter first number: "))
second_number = float(input("Enter second number: "))
third_number = float(input("Enter third number: "))

if first_number > second_number < third_number:
    print("The largest number is: ", first_number)
elif first_number == second_number > third_number:
    print("The largest number is: ", first_number)
elif second_number < first_number > third_number:
    print("The largest number is: ", first_number)
elif second_number < first_number == third_number:
    print("The largest number is: ", first_number)
elif first_number < second_number > third_number:
    print("The largest number is: ", second_number)
elif first_number < second_number == third_number:
    print("The largest number is: ", second_number)
elif first_number < second_number < third_number:
    print("The largest number is: ", third_number)
elif second_number < first_number < third_number:
    print("The largest number is: ", third_number)
elif first_number == second_number == third_number:
    print("The largest number is: ", first_number)
